site_name: IKIT for CARA
theme:
  name: material
  favicon: assets/favicon.ico
  palette:
    scheme: matchbox
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - IKIT Configuration: 'ikit-config.md'
  - IKIT Usecases: 'usecases.md'
  - EPR Primary System Integration: 'primarysystems-epr.md'
  - Transferts Integration: 'transferts.md'
  - PMP Integration: 'pmp.md'
  - CARA Requirements: 'requirements.md'
  - FAQ: 'faq.md'
  - CARA INT Changelog: 'changelog.md'
  - IKIT Changelog: 'changelog_ikit.md'
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
